language: node_js
node_js:
- "node"
env:
  - BUILD_DIR=client # here we define the subdirectory for travis as a global environment variable.

script:
  - if [ "$BUILD_DIR" = "client" ]; then cd $BUILD_DIR && npm install && npm run build; fi  # this script lets travis go into it and run any scripts we tell it to in the subdirectory we just declared above.

  
