language: node_js
node_js:
  - node
env:
  - Direction=src\client
  - Direction=src\server
script:
  - if [ "$Direction" = "client" ]; then cd $Direction && npm install && npm run build; fi
  - if [ "$Direction" = "server" ]; then cd $Direction && npm install ; fi